### model
model_name_or_path: /inspire/qb-ilm/project/wuliqifa/public/liujiaxi/models/gpt-oss-20b
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: full
lora_rank: 8
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: dpo_en_demo
template: gpt_oss
cutoff_len: 4096
max_samples: 1000
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/gpt-oss-20b/lora/dpo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

flash_attn: sdpa