### model
model_name_or_path: /inspire/qb-ilm/project/wuliqifa/public/liujiaxi/models/gpt-oss-20b
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora  
lora_rank: 8           
lora_alpha: 16         
lora_dropout: 0.05
lora_target: all       

# deepspeed: examples/deepspeed/ds_z3_config.json 

### dataset
dataset: todorl_sft_data
template: gpt_oss
cutoff_len: 18258      
max_samples: 3360
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/gpt-20b/sft/lora_rank8_stride_20 
logging_steps: 1
save_steps: 20
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 2  
gradient_accumulation_steps: 4  
save_total_limit: 3
learning_rate: 1.0e-4           
num_train_epochs: 3.0           
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
gradient_checkpointing: true

flash_attn: fa2