### model
model_name_or_path: ./models/Qwen3-14B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: todorl_sft_data
template: qwen3          
cutoff_len: 18258          
max_samples: 3360
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3-14b/full/sft_stride_20
logging_steps: 1
save_steps: 20            
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1      
gradient_accumulation_steps: 8      
learning_rate: 5.0e-6               
num_train_epochs: 2.5               
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
gradient_checkpointing: true        

flash_attn: fa2                     

