### model
model_name_or_path:
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.1
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: todorl_dpo_data
template: qwen
cutoff_len: 18258
max_samples: 2000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3-14b/full/dpo_final
logging_steps: 1
save_steps: 4
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 5.0e-7
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
gradient_checkpointing: true

flash_attn: fa2